local functions = require("lib.functions")

data:extend({
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_energy",
		icon = "__z_yira_yuokirails__/graphics/icons/4a_cw_energy1_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_energy"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_eb1",
		icon = "__z_yira_yuokirails__/graphics/icons/4a_cw_eb_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_eb1"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_gears",
		icon = "__z_yira_yuokirails__/graphics/icons/4a_cw_gears_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_gears"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_kiste1",
		icon = "__z_yira_yuokirails__/graphics/icons/4a_cw_kiste_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_kiste1"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_ziegelgrau",
		icon = "__z_yira_yuokirails__/graphics/icons/4a_cw_ziegel_grau_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_ziegelgrau"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_ziegelrot",
		icon = "__z_yira_yuokirails__/graphics/icons/4a_cw_ziegel_rot_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_ziegelrot"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_yiblue",
		icon = "__z_yira_yuokirails__/graphics/icons/4aw_cargo_yiblue_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_yiblue"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_yigreen",
		icon = "__z_yira_yuokirails__/graphics/icons/4aw_cargo_yigreen_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_yigreen"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_kisten",
		icon = "__z_yira_yuokirails__/graphics/icons/4aw_cw_kiste1_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_kisten"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_stuff1",
		icon = "__z_yira_yuokirails__/graphics/icons/4aw_cw_stuff1_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_stuff1"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "y_3acw_T10K",
		icon = "__z_yira_yuokirails__/graphics/icons/vs_test_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "y_3acw_T10K"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -1.1}, {0.6, 1.1}},
		selection_box = {{-0.7, -1.2}, {1, 1.2}},
		weight = 1000,
		max_speed = 1.2,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		connection_distance = 2.2,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_4a_cw_steel",
		icon = "__z_yira_yuokirails__/graphics/icons/4a_steel_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_4a_cw_steel"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 2,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
	},
	{
		type = "cargo-wagon",
		name = "z_yira_6a_maai1",
		icon = "__z_yira_yuokirails__/graphics/icons/6a-special-1-icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 40,
		minable = {mining_time = 0.5, result = "z_yira_6a_maai1"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 500,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.6}, {0.6, 2.6}},
		selection_box = {{-1, -3}, {1, 3}},
		connection_distance = 3,
		joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		vertical_selection_shift = -0.5,
		energy_per_hit_point = 5,
		tie_distance = 50,
	}
})
