local functions = require("lib.functions")

data:extend({
	{
		type = "cargo-wagon",
		name = "yir_us_cargo",
		icon = "__z_yira_yuokirails__/graphics/icons/usw_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 10,
		minable = {mining_time = 0.5, result = "yir_us_cargo"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 400,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -1.1}, {0.6, 1.1}},
		selection_box = {{-0.9, -1.5}, {0.9, 1.5}},
		weight = 500,
		max_speed = 1,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		connection_distance = 2.2,
		joint_distance = 1.1,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
		horizontal_doors =
		{
			layers =
			{
				{
					filename = "__z_yira_yuokirails__/graphics/usw_we.png",
					line_length = 1,
					width = 256,
					height = 256,
					frame_count = 1,
					shift = {0, -0.625},
					--animation_speed = 10,
				}
			}
		},
		vertical_doors =
		{
			layers =
			{
				{
					filename = "__z_yira_yuokirails__/graphics/usw_ns.png",
					line_length = 1,
					width = 256,
					height = 256,
					frame_count = 1,
					shift = {0, -0.625},
				}
			}
		},
		tie_distance = 50,
	},
	{
		type = "cargo-wagon",
		name = "yir_cw_cargo_green",
		icon = "__z_yira_yuokirails__/graphics/icons/2aw_cargo_green_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 20,
		minable = {mining_time = 0.5, result = "yir_cw_cargo_green"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 400,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -1.1}, {0.6, 1.1}},
		selection_box = {{-0.9, -1.5}, {0.9, 1.5}},
		weight = 750,
		max_speed = 1,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
	{
		type = "cargo-wagon",
		name = "yir_cw_cargo_blue",
		icon = "__z_yira_yuokirails__/graphics/icons/2aw_cargo_blue_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 20,
		minable = {mining_time = 0.5, result = "yir_cw_cargo_blue"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 400,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -1.1}, {0.6, 1.1}},
		selection_box = {{-0.9, -1.5}, {0.9, 1.5}},
		weight = 750,
		max_speed = 1,
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		vertical_selection_shift = -0.5,
		tie_distance = 50,
		wheels = functions.standard_train_wheels,
	},
})